### ISSUE TITLE
Issues I had with literate while trying to build your slides

### ISSUE THREAD

**Issue by alyssadev** [0atman/noboilerplate#3]
Hey there. First time doing anything at all with Rust, your videos came up in the ol recommended feed and they're very friendly and affirming, it's a great presentation style.
Did everything in your Rust lightsaber video, love neovide, thanks for the tip there. Tried to build your slides here, ran into issues with literate that could benefit from some notes in scripts/readme.md. The main ones being:

* literate doesn't have docs on how to build the cli binary
* cargo install wouldn't install literate without a Cargo.toml file which literate was meant to generate
* after cloning the literate-rs repo and running cargo build and cargo install, it still didn't create the binary
* eventually i ran cargo run and it said i needed to build it again with `--features=cli`, this wasn't documented anywhere upstream that i could find, maybe it's common knowledge among rust developers
* once i ran `cargo install --release --features=cli` in the literate-rs directory, it was finally installed

i'm assuming the one command needed to get this to work in the first place was `cargo install literate --features=cli`. After this and installing cargo-script, which went smoothly, the rust lightsaber markdown document is now compiling via make build.

**Comment by alyssadev** [comment]
And it's probably out of scope for this repo specifically and something best added to the literate-rs project in documentation, but I didn't want to commit the faux pas of assuming that something is a mistake in a new community and then to be told "oh no this is a completely normal thing that you've entirely misunderstood".

**Comment by 0atman** [comment]
Sorry I didn't expect issues in this repo - but I'm very glad to have them!

Yes, thank you very much for the reminder, I will update my readmes

**Comment by 0atman** [comment]
BTW I suspect I downloaded a precompiled binary https://github.com/misalcedo/literate-rs/releases/tag/v0.5.1

**Comment by 0atman** [comment]
From video 9 onwards I have much streamlined the process, apologies that I don't yet have time to retro-actively fix the old scripts

**Comment by 0atman** [comment]
Thank you for the issue.
