### ISSUE TITLE
todo: change script names to be in line with YouTube 

### ISSUE THREAD

**Issue by laundmo** [0atman/noboilerplate#35]
this is a bit confusing since they dont match YouTube titles. oldfartdeveloper in discord VC mentioned this.

**Comment by oldfartdeveloper** [comment]
+1

I find I want to review to get specific text information that I see in the YouTube where it is extremely tedious to find.

(Thanks @laundmo)

**Comment by 0atman** [comment]
yeah, it's a shame the youtube meta forces me to constantly rename the videos. one of the reasons I number the scripts is to keep the link between them, but I see now that I don't then also put that number in the video! 
I think I can solve all of this with a direct link to the markdown in the video description. Thanks all, I'll do that now.
