### ISSUE TITLE
CSS for Advanced Slides

### ISSUE THREAD

**Issue by BurntNail** [0atman/noboilerplate#37]
Hey @0atman,

I've been having a look over at Advanced Slides for Obsidian and I'm loving it! You seem to be using the `black` theme for it, but I can't quite work out what your highlight theme. Is it something custom? I'm just asking because the default themes don't appear to cut the mustard for code highlighting.

If you don't want to share, then no worries!

**Comment by 0atman** [comment]
Sorry I missed this! This is the vs2015 highlight theme, as well as the black theme.
