### ISSUE TITLE
Obsidian Wiki Style Links don't render correctly on GitHub, Gitlab, Pandoc

### ISSUE THREAD

**Issue by K1ngjulien** [0atman/noboilerplate#42]
Heyo!

I've been a fan of both your channel and obsidian for a while now and I have noticed the following issue.

When storing Obsidian's markdown in places like GitHub and co, which all provide a markdown viewer they unfortunately cannot render the "wikilink" style notation of obsidian flavoured markdown

These just render as regular text:
```markdown
[[www.google.com]] or [[www.google.com |link to google]]

![[https://github.com/0atman/noboilerplate/assets/16562333/c5d35f9e-f257-4a32-ae29-b05fdca507a0]]
```
[[www.google.com]] or [[www.google.com |link to google]]

![[https://github.com/0atman/noboilerplate/assets/16562333/c5d35f9e-f257-4a32-ae29-b05fdca507a0]]

But the standard markdown syntax shows up just fine:
```markdown
<https://google.com>

[link to google[(https://peertube.be/w/v8w9Px3AvSMp7gF827JuPg?autoplay=1)

![image](https://github.com/0atman/noboilerplate/assets/16562333/c5d35f9e-f257-4a32-ae29-b05fdca507a0)
```

<https://google.com>

[link to google](https://peertube.be/w/v8w9Px3AvSMp7gF827JuPg)

![image](https://github.com/0atman/noboilerplate/assets/16562333/c5d35f9e-f257-4a32-ae29-b05fdca507a0)

# more examples:

especially the width assignment with the `[[...|500]]` you can forget...

![image](https://github.com/0atman/noboilerplate/assets/16562333/f1de44c6-1919-47ed-af7f-a8bc2facf9ce)

![image](https://github.com/0atman/noboilerplate/assets/16562333/57e85ec8-4855-410d-a1da-51b5c4402736)

The same issue has been occuring to me when trying to generate nice PDFs with a latex pandoc template, since pandoc also doesn't like those links.

the options to mee seem to be:
- Write a browser extension to patch the GitHub UI rendering until official channels fix it (probably never)
- write a lua or json filter for pandoc that converts the wiki style links to markdown links but that seems like a bunch of work :sweat_smile: 
    - but honestly getting some tree traversal practice couldnt hurt :P 
- The obsidian output to pdf function obviously works like a charm, but doesn't allow me to use filters and latex templates to create indexes, toc, title pages and so on.
    - For a start it would be nice to change the default template for pdf export.
 
Do you have any Ideas on this? 

Cheers,
K1ngjulien

**Comment by 0atman** [comment]
Slant suggestion: Github Wikis DO render `[[this format]]`. Maybe I should switch the script to the wiki... lemme try, thank you!

**Comment by 0atman** [comment]
Hey, this works GREAT! https://github.com/0atman/noboilerplate/wiki/Test-Presentation

**Comment by 0atman** [comment]
What do you think, should I migrate the scripts into the wiki?

**Comment by 0atman** [comment]
hmm ok this has multiple disadvantages that I think mean I should find another way. No PRs is especially annoyinng...

**Comment by K1ngjulien** [comment]
lmao I'd totally forgotten about this issue.
unfortunately i haven't found a good workaround either... (nor have i really had the time to try)

writing a couple lines of regex to change wiki links to regular markdown shouldn't be too hard, right? :D

the wiki not having PRs is kind of weird imo, yea i get it's in the spirit of wikipedia where everyone can edit but i'm not sure i'd want that lol
and i fear many people would miss the wiki unless there was a giant link to it in the readme.md

**Comment by 0atman** [comment]
I have fixed this by switching to absolute markdown links in my videos - thanks for reporting!
