### ISSUE TITLE
Create LICENSE.md

### ISSUE THREAD

**Issue by wertercatt** [0atman/noboilerplate#56]
https://github.com/0atman/noboilerplate/blob/main/scripts/36-Linux-Workstations.md#public-domain-videos

All of your videos have this section near the beginning of them. Despite this, there isn't actually a LICENSE file in this GitHub repo. The Creative Commons logo doesn't explicitly refer to any specific license. Based on the phrase 'public domain license' I could make the assumption that you mean [CC0](https://creativecommons.org/publicdomain/zero/1.0/) but that likely wouldn't hold up in court. Please add an explicit license file, thank you.

**Comment by Sprocketer** [comment]
@0atman I back this ^ protect your work 👍

**Comment by 0atman** [comment]
I thought I already had, how strange! Thanks for the reminder, done: https://github.com/0atman/noboilerplate/blob/main/LICENSE
