### ISSUE TITLE
Share the full setup to make a video

### ISSUE THREAD

**Issue by azzamsa** [0atman/noboilerplate#75]
Hi, 👋🏽 

I see some of the tools mentioned, such as obsidian, and reaper.fm.
But you don't mention the mic, video editor, etc.

Would you like to share your full setup to create such a simple but informative video?

Thank you 🥞

**Comment by 0atman** [comment]
Thanks for your interest! The software is certainly simper than you're imagining: As I say in the readme of this repo: It's literally obsidian and reaper - nothing more!

> I build these using [obsidian.md](https://obsidian.md/) and the [advanced-slides plugin](https://github.com/MSzturc/obsidian-advanced-slides): I take each slide, printscreen it, and splice it with my audio using [reaper.fm](http://reaper.fm/).
https://github.com/0atman/noboilerplate/blob/main/README.md

That's right, reaper does both audio AND video editing!

Hardware changes quite often (I'm always trying to optimise!) and you'll find them in each video description so you can hear the differences.

But my current recommendation is simple: NT1v5. A single usb mic, no other equipment required.
(great review here https://www.youtube.com/watch?v=5uyBYnoZB5k)

**Comment by azzamsa** [comment]
Thank you so much for taking time to reply and very thorough response 🥞

**Comment by 0atman** [comment]
Pleasure! Now you know how easy it is, what's stopping you making your own? :wink: 

post your creations on my Discord over in `#your-projects` and the lovely community will give support and feedback :tada:
