### ISSUE TITLE
Thread panic on station breakdown

### ISSUE THREAD

**Issue by Mitch557** [0atman/noboilerplate#9]
### Issue:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidConfiguration("Available options can not be empty")

### Steps to reproduce:
Continually select "SCIENCE" on each day without repairing. About 50% of the time the thread panics. The other half, the game ends normally.

### Possible explanation:
When the number of active sections is down to 1 and "NEW DAY" is selected there is a chance the final section breaks. If this occurs the user still has the opportunity to select "SCIENCE" but there are no active sections to enumerate in the menu.

**Comment by 0atman** [comment]
Well spotted! I didn't battle test this code very much, I bet there's loads of logical errors with my game loop, I should have tested more, but I ran out of time.

**Comment by 0atman** [comment]
I've added a note about this to the ERRATA comment, as though it's a bug, it's not the main point of the video. Thank you again!
